"""Board to Typst source (SPEC §4, §7)."""

from __future__ import annotations

from typing import Callable, Optional

from . import style as styles
from .board import Board
from .project import IMAGE_KINDS

LIBRARY = "_pintu.typ"
LIBRARY_PATH = "/boards/build/" + LIBRARY


def _num(v: float) -> str:
    return f"{float(v):.6g}"


def typst_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def panel_source(panel: dict, exists: Callable[[str], bool]) -> tuple[Optional[str], str, str]:
    """How to draw a panel's source.

    Returns:
        (root-relative file or None, kind "vector"/"raster", placeholder label).
    """
    src = panel.get("source") or {}
    pid = panel["id"]
    if "file" in src:
        f = str(src["file"])
        kind = IMAGE_KINDS.get("." + f.rsplit(".", 1)[-1].lower()) if "." in f else None
        if kind is None:
            return None, "vector", f"{pid}: unsupported file {f}"
        if not exists(f):
            return None, kind, f"{pid}: missing file {f}"
        return f, kind, pid
    if "recipe" in src:
        return None, "vector", f"{pid}: recipe {src['recipe']} (not rendered yet)"
    return None, "vector", pid


def generate(board: Board, exists: Callable[[str], bool], name: str = "") -> str:
    """Typst source for a board.

    Args:
        board: The board.
        exists: Whether a project-relative file exists and is inside the root.
        name: Board name, for the header comment.
    """
    page = board.page
    st = styles.get(board.style)
    lt = st["letter"]
    letters = board.letters()
    fonts = "(" + ", ".join(typst_str(f) for f in st["font"]) + ",)"
    lines = [
        f"// Generated by pintu from boards/{name}.board.yaml; do not edit.",
        f'#import "{LIBRARY_PATH}": *',
        f"#let W = {_num(page.width)}mm",
        f"#let H = {_num(page.height)}mm",
        f"#let G = ({page.nx}, {page.ny})",
        f"#show: board-page.with(width: W, height: H, font: {fonts}, size: {_num(st['font_size_pt'])}pt)",
    ]
    for p in board.panels:
        f, kind, label = panel_source(p, exists)
        letter = letters.get(p["id"])
        if letter is not None and lt["lower"]:
            letter = letter.lower()
        c = p["cell"]
        args = [
            "W", "H", "G", f"({c[0]}, {c[1]}, {c[2]}, {c[3]})",
            f"gutter: {_num(page.gutter)}mm",
            f"src: {typst_str('/' + f) if f else 'none'}",
            f"kind: {typst_str(kind)}",
            f"label: {typst_str(label)}",
            f"letter: {typst_str(letter) if letter else 'none'}",
            f"zone: {_num(lt['zone_mm'])}mm",
            f"letter-size: {_num(lt['size_pt'])}pt",
        ]
        lines.append(f"#board-panel({', '.join(args)})")
    return "\n".join(lines) + "\n"
